services:
  - type: web
    name: arshith-fresh
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SHIPROCKET_EMAIL
        sync: false
      - key: SHIPROCKET_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
